keyword=Java Developer
experience=0-2 years
locations=Bangalore,Hyderabad,Chennai,Mumbai,Noida,Gurugram
maxApplications=100
chromeProfilePath=C:/Users/rkumar72/Downloads/project/job silenium/chrome-profile
headless=false
excelReportPath=reports/applied_jobs.xlsx
